# Generated by Django 2.2.17 on 2020-11-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveIntegerField(choices=[(0, 'Pending'), (1, 'Live'), (2, 'Archived')], default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
