# Generated by Django 2.2.17 on 2020-11-11 23:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='launch_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='tile',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Live'), (1, 'Draft'), (2, 'Pending'), (3, 'Archived')], default=0),
        ),
    ]
