# Generated by Django 2.2.17 on 2020-11-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=250)),
                ('task_type', models.PositiveIntegerField(choices=[(0, 'Unassigned'), (1, 'Survey'), (2, 'Discussion'), (3, 'Diary')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.CharField(blank=True, max_length=15)),
            ],
        ),
    ]
